#!/usr/bin/env python3
"""Build the self-contained, publishable copy of the investigation.

story.html fetches article_data.json at runtime, which is convenient inside the
repository but means the page needs a web server and the data file beside it.
This script folds the data into the HTML and rewrites the outbound links to the
published site, producing one file that works anywhere — double-clicked from
disk, dropped into a CMS, or attached to an email.

    python3 build_publish.py                 # -> egp-investigation.html
    python3 build_publish.py --base ''       # keep links relative
    python3 build_publish.py -o out.html

The published site's front page is this same build with relative links, because
GitHub Pages serves the repository root and the PDFs sit beside the page:

    python3 build_publish.py -o index.html --base ''

Nothing is edited by hand in the output: rerun this after article_data.json or
story.html changes.
"""

import argparse
import datetime
import io
import json
import os
import re
import sys

SRC_HTML = "story.html"
SRC_DATA = "article_data.json"
OUT = "egp-investigation.html"
BASE = "https://tusher984.github.io/EGP/"
SIBLINGS = ("tool.html", "investigation.html", "findings.html")
# The typeface is served from the repository, so an off-site copy of the page has to
# point at it absolutely or fall back to the system sans — and lose the Bangla face.
FONT_REF = '"fonts/LiAdorNoirritMultiweight/'
FONT_REFS = 6          # 2 preload links + 4 @font-face sources


def die(msg):
    sys.stderr.write("build_publish: %s\n" % msg)
    raise SystemExit(1)


def read(path):
    if not os.path.exists(path):
        die("%s not found — run this from the repository root." % path)
    return io.open(path, encoding="utf-8").read()


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--out", default=OUT, help="output file (default %s)" % OUT)
    ap.add_argument("--base", default=BASE,
                    help="absolute base for source-PDF and sibling-page links; "
                         "pass an empty string to keep them relative")
    args = ap.parse_args()

    html = read(SRC_HTML)
    raw = read(SRC_DATA)
    try:
        data = json.loads(raw)
    except ValueError as exc:
        die("%s is not valid JSON: %s" % (SRC_DATA, exc))

    cases = data.get("cases") or []
    if not cases:
        die("%s carries no `cases` array — nothing to publish." % SRC_DATA)

    base = args.base.strip()
    if base and not base.endswith("/"):
        base += "/"

    # Minified, and with `<` escaped so no value can close the script element early.
    blob = json.dumps(data, separators=(",", ":"), ensure_ascii=False).replace("<", "\\u003c")

    stamp = datetime.date.today().isoformat()
    head = (
        "<!--\n"
        "  e-GP Watch — the complete investigation, as one self-contained file.\n"
        "  Built %s by build_publish.py from story.html + %s.\n"
        "  Do not edit this file: edit story.html and rebuild.\n"
        "\n"
        "  %s awards - %s crore - %s source PDFs. Every named firm, office and\n"
        "  official appears because the public e-GP record names them. Every pattern\n"
        "  is a red flag warranting scrutiny, not a finding of wrongdoing.\n"
        "\n"
        "  Source documents, fonts and the sibling pages are linked to %s\n"
        "  Change the data-pdf-base attribute on <body> to point them elsewhere.\n"
        "-->\n"
    ) % (stamp, SRC_DATA, len(cases),
         format(data["headline"]["value_crore"], ",.1f"),
         format(data["headline"]["pdfs"], ","),
         base or "the folder beside this file.")

    out = html
    if not out.lstrip().startswith("<!DOCTYPE"):
        die("story.html does not start with a doctype — refusing to guess.")

    # 1 · absolute base for the 1,290 source-PDF links
    if out.count("<body>") != 1:
        die("expected exactly one plain <body> tag in story.html")
    out = out.replace("<body>", '<body data-pdf-base="%s">' % base, 1)

    # 2 · absolute base for the sibling pages, so the nav still works off-site
    if base:
        for name in SIBLINGS:
            out = out.replace('href="%s"' % name, 'href="%s%s"' % (base, name))

    # 2b · absolute base for the four font files, so the Bangla and Latin faces
    #      still load when the page is opened from disk or from another domain
    if out.count(FONT_REF) != FONT_REFS:
        die("expected %d references to %s in story.html, found %d — update this script"
            % (FONT_REFS, FONT_REF, out.count(FONT_REF)))
    if base:
        out = out.replace(FONT_REF, '"%sfonts/LiAdorNoirritMultiweight/' % base)

    # 3 · the dataset itself, immediately before the application script
    marker = "\n<script>\n"
    if out.count(marker) != 1:
        die("could not find the single application <script> tag to inject before")
    inject = ('\n<!-- article_data.json, inlined: this page makes no network request for data -->\n'
              '<script id="story-data" type="application/json">%s</script>\n' % blob)
    out = out.replace(marker, inject + marker, 1)

    # 4 · build banner above the doctype (last, so its own <body> mention is not rewritten)
    out = head + out

    # 5 · checks that the result is actually self-contained
    if 'id="story-data"' not in out:
        die("injection failed")
    if "fetch('article_data.json'" not in out:
        die("the fetch fallback vanished — story.html changed shape; update this script")

    io.open(args.out, "w", encoding="utf-8").write(out)

    kb = os.path.getsize(args.out) / 1024.0
    print("wrote %s — %.0f KB, self-contained" % (args.out, kb))
    print("  %s awards - %s crore - %s contractors - %s source PDFs"
          % (len(cases), format(data["headline"]["value_crore"], ",.1f"),
             format(data["concentration"]["suppliers"], ","),
             format(data["headline"]["pdfs"], ",")))
    print("  links resolve to %s" % (base or "paths relative to the file"))


if __name__ == "__main__":
    main()
